create table if not exists public.pro_item_timings (
  id bigint generated by default as identity primary key,
  hero_id integer not null,
  hero_name text not null,
  item_key text not null,
  item_name text not null,
  role text not null default 'hard_carry',
  scenario text not null default 'stomp',
  optimal_minute numeric(5,2) not null,
  min_minute numeric(5,2),
  max_minute numeric(5,2),
  patch text,
  source text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_pro_item_timings_lookup
  on public.pro_item_timings (hero_id, role, scenario);

create unique index if not exists idx_pro_item_timings_unique_current
  on public.pro_item_timings (hero_id, item_key, role, scenario, coalesce(patch, 'current'));

insert into public.pro_item_timings
  (hero_id, hero_name, item_key, item_name, optimal_minute, min_minute, max_minute, source)
values
  (1, 'Anti-Mage', 'power_treads', 'Power Treads', 8, 7, 10, 'manual benchmark'),
  (1, 'Anti-Mage', 'bfury', 'Battle Fury', 14, 13, 15, 'manual benchmark'),
  (1, 'Anti-Mage', 'manta', 'Manta Style', 21, 19, 24, 'manual benchmark'),
  (8, 'Juggernaut', 'phase_boots', 'Phase Boots', 7, 6, 9, 'manual benchmark'),
  (8, 'Juggernaut', 'maelstrom', 'Maelstrom', 13, 12, 15, 'manual benchmark'),
  (41, 'Faceless Void', 'power_treads', 'Power Treads', 8, 7, 10, 'manual benchmark'),
  (41, 'Faceless Void', 'maelstrom', 'Maelstrom', 14, 12, 16, 'manual benchmark'),
  (44, 'Phantom Assassin', 'power_treads', 'Power Treads', 8, 7, 10, 'manual benchmark'),
  (44, 'Phantom Assassin', 'bfury', 'Battle Fury', 15, 13, 17, 'manual benchmark')
on conflict do nothing;
